### ISSUE TITLE
Remote pulseaudio server

### ISSUE THREAD

**Issue by darksaboteur** [stanford-oval/node-pulseaudio#43]
I'm trying to connect to a remote pulseaudio server on my local network
```
var context = new PulseAudio({
    "server": "192.168.0.131",
});
```
However when add the server I get Segmentation fault (core dumped) when I run it.

Is this a supported feature? I've tried with node 12, 14 and 16.

I'm not sure if it is related to all the errors thrown when installing the package?
```
$ npm rebuild

> pulseaudio2@0.5.0 install /home/nick/Desktop/audio-router/node_modules/pulseaudio2
> node-gyp configure build

make: Entering directory '/home/nick/Desktop/audio-router/node_modules/pulseaudio2/build'
  CXX(target) Release/obj.target/pulse/src/context.o
../src/context.cc: In member function ‘void pulse::Context::set_mute(pulse::InfoType, uint32_t, uint32_t, v8::Local<v8::Function>)’:
../src/context.cc:220:11: warning: enumeration value ‘INFO_SERVER’ not handled in switch [-Wswitch]
  220 |     switch(infotype) {
      |           ^
../src/context.cc:220:11: warning: enumeration value ‘INFO_MODULE_LIST’ not handled in switch [-Wswitch]
../src/context.cc: In member function ‘void pulse::Context::set_mute(pulse::InfoType, const char*, uint32_t, v8::Local<v8::Function>)’:
../src/context.cc:232:11: warning: enumeration value ‘INFO_SERVER’ not handled in switch [-Wswitch]
  232 |     switch(infotype) {
      |           ^
../src/context.cc:232:11: warning: enumeration value ‘INFO_MODULE_LIST’ not handled in switch [-Wswitch]
../src/context.cc: In member function ‘void pulse::Context::set_volume(pulse::InfoType, uint32_t, const pa_cvolume*, v8::Local<v8::Function>)’:
../src/context.cc:244:11: warning: enumeration value ‘INFO_SERVER’ not handled in switch [-Wswitch]
  244 |     switch(infotype) {
      |           ^
../src/context.cc:244:11: warning: enumeration value ‘INFO_MODULE_LIST’ not handled in switch [-Wswitch]
../src/context.cc: In member function ‘void pulse::Context::set_volume(pulse::InfoType, const char*, const pa_cvolume*, v8::Local<v8::Function>)’:
../src/context.cc:256:11: warning: enumeration value ‘INFO_SERVER’ not handled in switch [-Wswitch]
  256 |     switch(infotype) {
      |           ^
../src/context.cc:256:11: warning: enumeration value ‘INFO_MODULE_LIST’ not handled in switch [-Wswitch]
In file included from ../src/common.hh:27,
                 from ../src/context.hh:23,
                 from ../src/context.cc:20:
/home/nick/.cache/node-gyp/12.21.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/nick/.cache/node-gyp/12.21.0/include/node/node_object_wrap.h:85:25:   required from here
/home/nick/.cache/node-gyp/12.21.0/include/node/v8.h:10226:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
10226 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nick/.cache/node-gyp/12.21.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:64:57:   required from here
/home/nick/.cache/node-gyp/12.21.0/include/node/v8.h:10226:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
  CXX(target) Release/obj.target/pulse/src/stream.o
In file included from ../src/common.hh:27,
                 from ../src/stream.hh:23,
                 from ../src/stream.cc:20:
/home/nick/.cache/node-gyp/12.21.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/nick/.cache/node-gyp/12.21.0/include/node/node_object_wrap.h:85:25:   required from here
/home/nick/.cache/node-gyp/12.21.0/include/node/v8.h:10226:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
10226 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nick/.cache/node-gyp/12.21.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:64:57:   required from here
/home/nick/.cache/node-gyp/12.21.0/include/node/v8.h:10226:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
  CXX(target) Release/obj.target/pulse/src/uv-mainloop.o
In file included from ../src/common.hh:27,
                 from ../src/context.hh:23,
                 from ../src/uv-mainloop.cc:20:
/home/nick/.cache/node-gyp/12.21.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/nick/.cache/node-gyp/12.21.0/include/node/node_object_wrap.h:85:25:   required from here
/home/nick/.cache/node-gyp/12.21.0/include/node/v8.h:10226:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
10226 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nick/.cache/node-gyp/12.21.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:64:57:   required from here
/home/nick/.cache/node-gyp/12.21.0/include/node/v8.h:10226:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
  CXX(target) Release/obj.target/pulse/src/addon.o
In file included from ../../nan/nan.h:56,
                 from ../src/common.hh:28,
                 from ../src/addon.cc:20:
/home/nick/.cache/node-gyp/12.21.0/include/node/node.h:737:7: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  737 |       (node::addon_register_func) (regfunc),                          \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nick/.cache/node-gyp/12.21.0/include/node/node.h:771:3: note: in expansion of macro ‘NODE_MODULE_X’
  771 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/addon.cc:30:1: note: in expansion of macro ‘NODE_MODULE’
   30 | NODE_MODULE(NODE_GYP_MODULE_NAME, node_pulseaudio_init)
      | ^~~~~~~~~~~
In file included from ../src/common.hh:27,
                 from ../src/addon.cc:20:
/home/nick/.cache/node-gyp/12.21.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/nick/.cache/node-gyp/12.21.0/include/node/node_object_wrap.h:85:25:   required from here
/home/nick/.cache/node-gyp/12.21.0/include/node/v8.h:10226:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
10226 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nick/.cache/node-gyp/12.21.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:64:57:   required from here
/home/nick/.cache/node-gyp/12.21.0/include/node/v8.h:10226:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
  SOLINK_MODULE(target) Release/obj.target/pulse.node
  COPY Release/pulse.node
make: Leaving directory '/home/nick/Desktop/audio-router/node_modules/pulseaudio2/build'
pulseaudio2@0.5.0 /home/nick/Desktop/audio-router/node_modules/pulseaudio2
bindings@1.5.0 /home/nick/Desktop/audio-router/node_modules/bindings
file-uri-to-path@1.0.0 /home/nick/Desktop/audio-router/node_modules/file-uri-to-path
nan@2.14.2 /home/nick/Desktop/audio-router/node_modules/nan
```

**Comment by gcampax** [comment]
Those errors are warnings, and they are unrelated (they are unavoidable with recent g++ and v8).

I've tried connecting to a remote server before, but I used the PULSE_SERVER environment variable, not the "server" option. This module wraps the normal libpulse, so it should support anything that libpulse does.

To debug the segmentation fault, can you get a C++ stack trace?
To do so, compile the module in debug mode:
```
rm -fr build/Release
make -C build/ BUILDTYPE=Debug
```

Then run:
```
gdb --args node ./testcase.js
```
Run the program with `r`, wait for the crash, then use `bt full` to get the backtrace with local variables.

Thank you!

**Comment by thelamer** [comment]
@gcampax 
```
(gdb) bt full
#0  0x00005555566d0761 in uv_poll_start ()
No symbol table info available.
#1  0x00007ffff4230509 in io_new (a=0x7ffff423c020 <pulse::Context::mainloop_api>, fd=25, ev=(PA_IO_EVENT_INPUT | PA_IO_EVENT_OUTPUT), 
    cb=0x7ffff416a2b3, ud=0x7ffff432b780) at ../src/uv-mainloop.cc:107
        m = 0x555557a4f660
        e = 0x7ffff43264b0
        __func__ = "io_new"
#2  0x00007ffff416a205 in ?? () from /usr/lib/pulseaudio/libpulsecommon-16.1.so
No symbol table info available.
#3  0x00007ffff41705b9 in pa_iochannel_new () from /usr/lib/pulseaudio/libpulsecommon-16.1.so
No symbol table info available.
#4  0x00007ffff418a34c in ?? () from /usr/lib/pulseaudio/libpulsecommon-16.1.so
No symbol table info available.
#5  0x00007ffff4230376 in io_cb (p=0x7ffff4326d80, st=0, ev=2) at ../src/uv-mainloop.cc:67
        pa_ev = PA_IO_EVENT_OUTPUT
        e = 0x7ffff4326d80
#6  0x00005555566d95cc in ?? ()
No symbol table info available.
#7  0x00005555566c7f14 in uv_run ()
No symbol table info available.
#8  0x0000555555ab07e2 in node::SpinEventLoop(node::Environment*) ()
No symbol table info available.
#9  0x0000555555bb76e5 in ?? ()
No symbol table info available.
#10 0x0000555555bb849b in node::NodeMainInstance::Run() ()
No symbol table info available.
#11 0x0000555555b2fae0 in node::LoadSnapshotDataAndRun(node::SnapshotData const**, node::InitializationResult const*) ()
No symbol table info available.
#12 0x0000555555b32cd3 in node::Start(int, char**) ()
No symbol table info available.
#13 0x00007ffff7f809ca in ?? () from /lib/ld-musl-x86_64.so.1
No symbol table info available.
#14 0x00007ffff7f809a2 in ?? () from /lib/ld-musl-x86_64.so.1
No symbol table info available.
#15 0x00007fffffffed10 in ?? ()
No symbol table info available.
#16 0x0000000000000000 in ?? ()
No symbol table info available.
```

```
pulseaudio 16.1
Alpine Linux 3.17 (also occurs in Ubuntu Jammy, Fedora 37, Arch Linux, and Debian Bullseye)
```
Not sure if I did this right, just using `new PulseAudio({"server":"127.0.0.1"});` with `load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1` set in default.pa. 

Trying to set the lowest bar for replication this should be dead simple to replicate. I am doing this in a Docker container if this matters. 

Without server set it works fine. Also tried `PULSE_SERVER=127.0.0.1` with the same result.
